### ISSUE TITLE
About the motif-scaffolding targets

### ISSUE THREAD

**Issue by Kirito-Ausna** [blt2114/twisted_diffusion_sampler#1]
Hello! Thanks for your awesome work and efforts in open-source the RFDiffusion Motif-Scaffolding Benchmark. I have one question about the provided target structures. I would appreciate it if you can give me some guidance.

The question is that the structures in motif.pdb and target.pdb(e.g. IBCF.pdb, 1BCF_motif.pdb) are not aligned (or not being superimposed). So I can't figure out which part of the target corresponding to the motif. If I understand correctly, the motif should be a part of the target protein and I find in your code you also just took the motif according to the index without any displacements. So I am confused why the motif and the target structures are not superimposed.

Thanks again for your awesome work! Looking forward to your reply~

**Comment by blt2114** [comment]
Hello!  Thanks for your question!

The motif file (1BCF_motif.pdb) is centered at the origin while the full native pdb is not.   If you look only at the motif residues defined in the "contig syntax" within benchmark.csv you will see the residue ranges corresponding to the motif.

For an explanation of the contig syntax, take a look here: https://github.com/RosettaCommons/RFdiffusion?tab=readme-ov-file#motif-scaffolding

Let me know if you have remaining questions.

Thanks!
Brian

**Comment by Kirito-Ausna** [comment]
Hi, Brian! Thanks for your answer!
I understand why the 1BCF_motif.pdb and 1BCF.pdb are not align now. But I am still a little confuse about the sampling results. If I understand correctly, the generative samples can be superimposed with the motif as the motif structure is the guidance. 
I find it correct for a few samples, that the generative samples align and are superimposed with the motifs. But the others are not (e.g.1QJG). Could you please give some guidance?

**Comment by blt2114** [comment]
Hi Kirito, thanks for the message.  I'm glad the 1BCF case is now clear.

Can you provide greater detail in what you are seeing?  In particular, what specifically have you run, with what settings, and what aspect of which outputs are you looking at when you say they do not superimposed?

**Comment by Kirito-Ausna** [comment]
Hi, Brian! Sorry for the late response. 
For example, I ran the 1PRW case with the default sampling setting, as you recommended in your repo. I found the sampled results (sample_1.pdb, not the predicted structure in the self-consistency test) don't superimpose with the 1PRW_motif.pdb (in the motif_scaffolding/targets). 
![image](https://github.com/blt2114/twisted_diffusion_sampler/assets/60833761/e99061c8-cbde-4632-9e91-b5745b9ea17e)

I checked the codes that the coordinates of 1PRW_motif.pdb should be the guidance of the sampling process. It's because they share the same process procedure **save_motif_segments.load_contig_test_case** and both are centered at the origin according to your last message (But I couldn't find any codes that modify the CoM of motif.pdb to Zero, I did notice the **remove_com_from_tensor_7** in inference_motif_scaffolding.py, Sampler.run_sampling() to move the CoM of motifs to Zero)

It is quite weird and it will be greatly appreciated if you can give me some help. Thanks a lot!

**Comment by blt2114** [comment]
This looks good to me!  Is it correct to say this is more a problem with visualization than the observed motif-scaffolding performance?  The motif part looks pretty good to me, but indeed is shifted in its center of mass. In pymol, I might try using cealign (https://pymolwiki.org/index.php/Cealign) on the motif and the motif part of the generated scaffold.

You maybe are also interested in the implementation?  In the code that indexes into the motif part in a GPU-friendly, vectorized way the center of mass on of the motif-part of the scaffold is subtracted out here: https://github.com/blt2114/twisted_diffusion_sampler/blob/main/protein_exp/motif_scaffolding/twisting.py#L152

Does that help?  If not, please feel free to ask a more specific question.

**Comment by Kirito-Ausna** [comment]
Hi, Brian, Thank you very much for your response! Yes, the observed motif-scaffolding performance is pretty good, nice work!  And yes, of course we can align them during visualization. I am just a little curious and confused about the reason of the shift In its center of mass. I found that the CoM of the motif part of the generated scaffold is zero and this aligns with the motif guidance (i.e. the rigid_motifs in the code, which is centered at Zero as we both mentioned) but the saved motif.pdb after running save_motif_segments.py is neither centered at zero, nor at its original center(i.e, as my first question mentioned, the saved motif.pdb doesn't superimpose with the motif part of the full native pdb)

I think it's related to the code 'all_atom.compute_backbone(ru.Rigid.from_tensor_7(segs_stacked), psis)[0]' in save_motif_segments.py but I can't figure out the reason exactly. Thus, I would like to know about your opinions.

Thank you very much for your kind and timely responses again!

**Comment by blt2114** [comment]
I see. I believe it is because the motif part that is saved is taken out before the scaffold is centered to place the motif at the origin.  Is this problematic or otherwise important for what you are hoping to do with the code, or just a curiosity?

**Comment by Kirito-Ausna** [comment]
Thank you for your response! Yes, the centre shift between the generated motif and the saved motif is caused by what you said in your last response. I understand this. My confusion is about the saved motif.pdb after running save_motif_segments.py is neither centered at zero, nor at its original center. 

The save_motif_segments.py just took the motif out of the original pdb and saved it to motif.pdb without modifications to the motif coordinates, so I am confused why the centre shift I mentioned above exists.

I am just curious and thank you so much for the discussion.

**Comment by blt2114** [comment]
Yes, happy to have discussed!  Since the centering translation of the motif part does not impact the interpretation of the results I did not take thought to center the motif in one way or another.  And so I suppose there is no reason to expect that it should be centered.  So I will close this issue.

If you would like the code to center the motif before output, feel free to re-open this issue and open a pull request with a change that uses a different translation of the motif in the saved pdb file.
