### ISSUE TITLE
Potential Typo in Code

### ISSUE THREAD

**Issue by zedt123** [blt2114/twisted_diffusion_sampler#3]
Hi,

First I would like to thank you for the great work! I have been looking through the code and I noticed a potential typo in the GaussianDiffusion class of smc_diffusion.py in image_diffusion.

The q_sample method uses as standard variation self.sqrt_one_minus_alphas_cumprod[t] * x_start which is sqrt(1-alpha_bar) * x_0. I think the correct formula is just sqrt(1-alpha_bar), so the code should instead be: scale = self.sqrt_one_minus_alphas_cumprod[t] * th.ones_like(x_start)

**Comment by LuhuanWu** [comment]
Hi, 

Thank you so much for pointing out the typo and your interest in the work! I have corrected the code, and so now it is 
`scale = self.sqrt_one_minus_alphas_cumprod[t] * th.ones_like(x_start)`. I should also add that this function does not seem to be used by our algorithm.
