### ISSUE TITLE
Question on SMC Implementation

### ISSUE THREAD

**Issue by zedt123** [blt2114/twisted_diffusion_sampler#4]
Reference: https://github.com/blt2114/twisted_diffusion_sampler/blob/d89d25046d13bdfdc23db4244c28544f97a07d00/smc_utils/feynman_kac_pf.py#L87C21-L87C64

Hi, I was wondering why you are adding the logarithm of the number of particles after normalizing the weights. Are there any numerical stability benefits to it?

Thank you!

**Comment by LuhuanWu** [comment]
Hi,

Adding the log P term (P for number of particles) is required for estimating the unnormalized constant, namely p(y)= \int p(x)p(y|x)dx. However, if the goal is to approximate the distribution p(x|y), having this term is not necessary.

**Comment by zedt123** [comment]
Thank you for the reply! This makes sense.
